WITH VALID_REFINE AS( --BASELINE LISTING DATA 5,774 ROWS
SELECT 
   LISTING_ID,
   YEAR_BUILT,
   ZIPCODE,
   PRICE,
   BEDROOMS,
   BATHROOMS,
   SQ_FT,
   DESCRIPTION,
   ACRES,
   CAR_GARAGE,
   PATIOS,
   GARAGE_TYPE,
   HOME_EXTERIOR,
   ROOF_TYPE,
   AMENITIES,
   HEATING,
   COOLING,
   FLOORING,
   ELEMENTARY,
   JR_HIGH,
   HIGH_SCHOOL,
   SCHOOL_DISTRICT,
   GEOGRAPHY,
   ROW_NUMBER() OVER (PARTITION BY ST_ASTEXT(GEOGRAPHY) ORDER BY LISTING_ID) AS ROW_NUM --VALUEs > 1 INDICATE DUPLICATE GEOMETRY,  ROW_NUM = 1 IS REFINED LISTING DATA, NO DUPLICATES
FROM UTAH_HOUSE_LISTINGS
),
ALL_DIST_HWY AS --BUILDS DISTANCE TABLE FROM HIGHWAY RAMPS TO ALL HOUSES
  (SELECT 
    R.ID,
    H.LISTING_ID,
    ST_DISTANCE(R.GEOGRAPHY,H.GEOGRAPHY) AS DIST --GENERATES MINIMUM GEODESIC DISTANCE IN METERS BETWEEN HIGHWAY RAMPS AND HOUSES
    FROM VALID_REFINE  H
    LEFT JOIN UTAH_RAMPS R ORDER BY 2,3),
 SHORTEST_DIST_HWY AS 
  (SELECT MIN(DIST) AS MIN_HWY_DIST, LISTING_ID FROM ALL_DIST_HWY GROUP BY LISTING_ID) --SELECTS SHORTEST DISTANCE BETWEEN EACH HOUSE AND HIGHWAY RAMPS FROM HIGHWAY DISTANCES TABLE
,
ALL_DIST_SKI AS --BUILDS DISTANCE TABLE FROM RECREATIONAL SKI AREAS TO ALL HOUSES
  (SELECT 
    S.NAME,
    H.LISTING_ID,
    ST_DISTANCE(S.GEOGRAPHY,H.GEOGRAPHY) AS DIST --GENERATES MINIMUM GEODESIC DISTANCE IN METERS BETWEEN SKI AREA AND HOUSES
    FROM VALID_REFINE  H
    LEFT JOIN UTAH_SKI_SNOWFLAKE S ORDER BY 2,3),
 SHORTEST_DIST_SKI AS 
  (SELECT MIN(DIST) AS MIN_SKI_DIST, LISTING_ID FROM ALL_DIST_SKI GROUP BY LISTING_ID)  --SELECTS SHORTEST DISTANCE FROM EACH HOUSE TO SKI AREA FROM THE SKI DISTANCES TABLE
SELECT     --STRUCTURING ENRICHED DATA TABLE WITH 
   HH.LISTING_ID,--BASELINE RAW DATA
   YEAR_BUILT,--BASELINE RAW DATA
   ZIPCODE,--BASELINE RAW DATA
   PRICE,--BASELINE RAW DATA
   BEDROOMS,--BASELINE RAW DATA
   BATHROOMS,--BASELINE RAW DATA
   SQ_FT,--BASELINE RAW DATA
   DESCRIPTION,--BASELINE RAW DATA
   ACRES,--BASELINE RAW DATA
   CAR_GARAGE,--BASELINE RAW DATA
   PATIOS,--BASELINE RAW DATA
   GARAGE_TYPE,--BASELINE RAW DATA
   HOME_EXTERIOR,--BASELINE RAW DATA
   ROOF_TYPE,--BASELINE RAW DATA
   AMENITIES,--BASELINE RAW DATA
   HEATING,--BASELINE RAW DATA
   COOLING,--BASELINE RAW DATA
   FLOORING,--BASELINE RAW DATA
   ELEMENTARY,--BASELINE RAW DATA
   JR_HIGH,--BASELINE RAW DATA
   HIGH_SCHOOL,--BASELINE RAW DATA
   SCHOOL_DISTRICT,--BASELINE RAW DATA
   RANK_SCORE, --SCHOOL DISTRICT SCORE                                                                                  
   TOTAL_POP,--ACS CENSUS                                                                                                
   HOUSEHOLDS,--ACS CENSUS                                                                                               
   MEDIAN_INCOME,--ACS CENSUS
   HOUSING_UNITS,--ACS CENSUS
   RENTER_OCCUPIED_HOUSING_UNITS_PAYING_CASH_MEDIAN_GROSS_RENT,--ACS CENSUS
   OCCUPIED_HOUSING_UNITS,--ACS CENSUS
   VACANT_HOUSING_UNITS,--ACS CENSUS
   VACANT_HOUSING_UNITS_FOR_RENT,--ACS CENSUS
   VACANT_HOUSING_UNITS_FOR_SALE,--ACS CENSUS
   HOUSING_BUILT_2005_OR_LATER,--ACS CENSUS
   HOUSING_BUILT_2000_TO_2004,--ACS CENSUS
   HOUSING_BUILT_1939_OR_EARLIER,--ACS CENSUS
   MEDIAN_YEAR_STRUCTURE_BUILT,--ACS CENSUS
   OWNER_OCCUPIED_HOUSING_UNITS,--ACS CENSUS
   MILLION_DOLLAR_HOUSING_UNITS, --ACS CENSUS
   AGGREGATE_TRAVEL_TIME_TO_WORK, --ACS CENSUS
   COMMUTERS_BY_PUBLIC_TRANSPORTATION, --ACS CENSUS
   NATWALKIND as WALK_INDEX, --NATIONAL WALKABILITY SCORE
   MIN_HWY_DIST/1000 as HWY_DISTANCE, --CONVERTS GEODESIC DISTANCE TO NEAREST HIGHWAY RAMP IN METERS TO KILOMETERS
   MIN_SKI_DIST/1000 as SKI_DISTANCE, --CONVERTS GEODESIC DISTANCE TO NEAREST RECREATIONAL SKI AREA IN METERS TO KILOMETERS
   HH.GEOGRAPHY
FROM VALID_REFINE HH
             LEFT JOIN "UTAH_SCHOOL_SNOWFLAKE" S ON RTRIM(DISTRICT) = REPLACE(SCHOOL_DISTRICT, 'School District', '') --JOINS SCHOOL DISTRICT SCORING, RANK_SCORE
             LEFT JOIN "CENSUS_ACS_2018_BLOCK_GROUP" BG ON ST_CONTAINS(BG.GEOGRAPHY, HH.GEOGRAPHY)   --SPATIALLY JOINS RELEVANT AMERICAN COMMUNITY CENSUS DATA
             LEFT JOIN "WALK_INDEX_SNOWFLAKE" WI ON ST_CONTAINS(WI.GEOGRAPHY, hh.GEOGRAPHY)          --SPATIALLY JOINS WALKABILTIY INDEX
             LEFT JOIN SHORTEST_DIST_HWY HWY on HWY.LISTING_ID = HH.LISTING_ID                       --JOINS THE SHORTEST HIGHWAY DISTANCE TO EACH ROW FOR HOUSE LISTING
             LEFT JOIN SHORTEST_DIST_SKI SKI on SKI.LISTING_ID = HH.LISTING_ID                       --JOINS THE SHORTEST RECREATIONAL SKI AREA DISTANCE TO EACH ROW FOR HOUSE LISTING
WHERE HH.GEOGRAPHY IS NOT NULL AND ROW_NUM = 1         --OMITS MISSING GEOMETRY AND OMITS DUPLICATE GEOMETRY BECAUSE VALUEs > 1 INDICATE DUPLICATE GEOMETRY